title: "Sima Ramin"
description: "Resume"
logo: /assets/img/Sima.jpg
sima_downloads: true
theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
---
layout: page
title: "Courses"
permalink: /courses/
---
